spring:
  application:
    name: zuul
  
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#路由规则,缺省配置,可不写
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

#启用重试
zuul:
  retryable: true
  
  
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#暴露监控点  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  
